[package]
name = "chlorine"
description = "Atomic 17!"
version = "1.0.0-alpha"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

[target."cfg(not(windows))".dependencies]
libc = { version = "0.2", default-features = false }
