name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_no_features:
    runs-on: [ubuntu-latest, windows-latest, mac-latest]
    strategy:
      matrix:
        rust:
        - { toolchain: 1.31.0 }
        - { toolchain: stable }
        - { toolchain: beta }
        - { toolchain: nightly }
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust.toolchain }}
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        command: test
